version: '2'
services:
  mysql:
    build: mysql
    env_file:
      - .env
    volumes:
      - ./envs:/envs
      - /data/moodle-mysql:/var/lib/mysql
  moodle:
    build: moodle
    links:
      - mysql
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./envs:/envs
      - /data/letsencrypt:/etc/letsencrypt
